import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MatrixRain from "./ui/home/matrixRain";
import Provider from "./home/provider";
import getSession from "./lib/getSession";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();
  return (
    <html lang="en">
      <head></head>
      <body
        className={inter.className + " antialiased font-normal bg-neutral-950"}
      >
        <Provider session={session}>{children}</Provider>
      </body>
    </html>
  );
}
